# -*- coding: utf-8 -*-
"""Projeto - Digital Innovation One.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nR7Vs2W4syV2LCs5b33XE2Eaz-RN6l3q

# Análise da Vacinação contra a Covid-19 no Estado da Bahia

Os dados aqui exibidos são de acesso público e são disponibilizados pela própria secretaria atraves do seu site oficial

# Importando a base de dados
"""

# Importando as bibliotecas 

import pandas as pd
import matplotlib.pyplot as plt

# Realizando a importação da biblioteca para o upload da base de dados

from google.colab import files

arqquivo = files.upload()

# Lendo a base de dados e atribuindo a uma variavel

df = pd.read_excel('Doses Aplicadas_23-09.xlsx')

# Exibindo os 5 primeiros registros

df.head()

# Exibindo os 5 ultimos registros

df.tail()

# Exibindo todas as colunas 

df.columns.to_list()

# Exibindo o total de linhas e colunas

df.shape

"""# Tratando a base de dados"""

# Selecionado algumas colunas e atribuindo a uma variavel

colunas_selecionadas = df[
  ['Cód. IBGE',
   'Núcleo Regional de Saúde (NRS)',
   'Município',
   'Total de Doses Aplicadas - D1', 
   'Total de Doses Aplicadas - D2', 
   'Total de Doses Aplicadas - D3', 
   'Total de Doses Aplicadas - DU']]

# Retirando o registro que contem o 'Núcleo Regional de Saúde (NRS)' igual a Regionais de Saúde 

df_base = colunas_selecionadas.loc[colunas_selecionadas['Núcleo Regional de Saúde (NRS)'] != 'Regionais de Saúde']

# Exibindo o total de linhas e colunas

df_base.shape

# Renomeando as colunas

df_base = df_base.rename(columns = 
    {'Cód. IBGE':'Cod. IBGE',
     'Núcleo Regional de Saúde (NRS)':'Nucleo Regional de Saude (NRS)',
     'Município':'Municipio',
     'Total de Doses Aplicadas - D1':'1ª Dose - Doses Aplicadas',
     'Total de Doses Aplicadas - D2':'2ª Dose - Doses Aplicadas',
     'Total de Doses Aplicadas - D3':'Dose Reforco - Doses Aplicadas',
     'Total de Doses Aplicadas - DU':'Dose Unica - Doses Aplicadas'},
    inplace=False)

"""# Visualizando os dados e gerando informações"""

plt.style.use('ggplot') # Altera o estilo do grafico

# Exibindo o total de doses aplicadas por dose (Tablea)

df_totalVacinados = df_base[['1ª Dose - Doses Aplicadas',
                             '2ª Dose - Doses Aplicadas',
                             'Dose Reforco - Doses Aplicadas',
                             'Dose Unica - Doses Aplicadas']].sum().reset_index()

df_totalVacinados = df_totalVacinados.rename(columns={'index':'Dose', 0:'Total de Doses Aplicadas'})

df_totalVacinados

# Exibindo o total de doses aplicadas por dose (Grafico)

df_totalVacinados = df_base[['1ª Dose - Doses Aplicadas',
                             '2ª Dose - Doses Aplicadas',
                             'Dose Reforco - Doses Aplicadas',
                             'Dose Unica - Doses Aplicadas']].sum().plot.barh(
                                                                  title='Total de Vacindados por dose',
                                                                  color='pink')

plt.xlabel('Total de Vacinados')
plt.ylabel('Dose');

# Exibindo o total de doses aplicadas por dose e por nucleo regional de saude (Tabela)

df_base.groupby(['Nucleo Regional de Saude (NRS)'])[['1ª Dose - Doses Aplicadas', 
                                                     '2ª Dose - Doses Aplicadas',
                                                     'Dose Reforco - Doses Aplicadas', 
                                                     'Dose Unica - Doses Aplicadas']].sum()

# Exibindo o total de doses aplicadas por dose e por nucleo regional de saude (Grafico)

df_base.groupby(['Nucleo Regional de Saude (NRS)'])[['1ª Dose - Doses Aplicadas', 
                                                     '2ª Dose - Doses Aplicadas',
                                                     'Dose Reforco - Doses Aplicadas', 
                                                     'Dose Unica - Doses Aplicadas']].sum().plot.barh(
                                                                                        title='Total de Vacindados por NRS')

plt.xlabel('Total de Vacinados')
plt.ylabel('Núcleo Regional de Saúde');

# Exibindo o total de doses aplicadas por dose e por municipio (Tabela)

dosesAplicadasMunicipio = df_base.loc[df_base['Municipio'] == 'Riachão do Jacuípe']

dosesAplicadasMunicipio

# Exibindo a quantidade de municpios por nucleo regional de saude (Tabela)

df_MNRS = df_base['Nucleo Regional de Saude (NRS)'].value_counts().reset_index()


municipiosPorNRS = df_MNRS.rename(columns={'index':'Nucleo Regional de Saude (NRS)',
                                           'Nucleo Regional de Saude (NRS)':'Qtde Municipios'})

municipiosPorNRS

# Exibindo a quantidade de municpios por nucleo regional de saude (Grafico)

df_MNRS = df_base['Nucleo Regional de Saude (NRS)'].value_counts().plot.barh(
                                                                    title='Qtde de municpios por NRS',
                                                                    color='pink')

plt.xlabel('Qtde Municipios')
plt.ylabel('Núcleo Regional de Saúde');

print('The End, isso é tudo pessoal... Por enquanto')